passes/elim_const_expr: Rewrite using FunctionPass
BasicBlockPass has been declared as deprecated and its definition
is not shipped with LLVM 10 (at least on Fedora).

See: https://llvm.org/doxygen/classllvm_1_1BasicBlockPass.html

Fixes:
In file included from /ProStatA/passes/elim_const_expr.cc:9:
/ProStatA/passes/elim_const_expr.hh:19:55: error: expected class-name before ‘{’ token
   19 | struct EliminateConstExprPass : public BasicBlockPass {
      |                                                       ^
/ProStatA/passes/elim_const_expr.hh: In constructor ‘EliminateConstExprPass::EliminateConstExprPass()’:
/ProStatA/passes/elim_const_expr.hh:24:30: error: class ‘EliminateConstExprPass’ does not have any field named ‘BasicBlockPass’
   24 |   EliminateConstExprPass() : BasicBlockPass(ID) {}
      |                              ^~~~~~~~~~~~~~
In file included from /ProStatA/passes/elim_const_expr.cc:10:
/ProStatA/passes/passes.hh: At global scope:
/ProStatA/passes/passes.hh:36:7: error: ‘BasicBlockPass’ in namespace ‘llvm’ does not name a type; did you mean ‘BasicBlock’?
   36 | llvm::BasicBlockPass *createEliminateConstExprPass();
      |       ^~~~~~~~~~~~~~
      |       BasicBlock
/ProStatA/passes/elim_const_expr.cc:18:1: error: ‘BasicBlockPass’ does not name a type
   18 | BasicBlockPass *createEliminateConstExprPass() {
      | ^~~~~~~~~~~~~~
In file included from /usr/include/llvm/Pass.h:316,
                 from /ProStatA/passes/elim_const_expr.hh:12,
                 from /ProStatA/passes/elim_const_expr.cc:9:
/usr/include/llvm/PassSupport.h: In instantiation of ‘llvm::Pass* llvm::callDefaultCtor() [with PassName = EliminateConstExprPass]’:
/usr/include/llvm/PassSupport.h:95:28:   required from ‘llvm::RegisterPass<passName>::RegisterPass(llvm::StringRef, llvm::StringRef, bool, bool) [with passName = EliminateConstExprPass]’
/ProStatA/passes/elim_const_expr.cc:119:101:   required from here
/usr/include/llvm/PassSupport.h:76:76: error: cannot convert ‘EliminateConstExprPass*’ to ‘llvm::Pass*’ in return
   76 | template <typename PassName> Pass *callDefaultCtor() { return new PassName(); }
      |                                                                            ^
In file included from /ProStatA/passes/global_vars.cc:18:
/ProStatA/passes/passes.hh:36:7: error: ‘BasicBlockPass’ in namespace ‘llvm’ does not name a type; did you mean ‘BasicBlock’?
   36 | llvm::BasicBlockPass *createEliminateConstExprPass();
      |       ^~~~~~~~~~~~~~
      |       BasicBlock